// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4l4Xe9sPNJFSAdBajBYukhdRzuRYKjkA',
    appId: '1:568144474994:web:3aa1e8bf0c2cbac201a3eb',
    messagingSenderId: '568144474994',
    projectId: 'salon-app-adabc',
    authDomain: 'salon-app-adabc.firebaseapp.com',
    storageBucket: 'salon-app-adabc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlVaT8YSPEpCUKCvmir6KJA_TLijj-D8c',
    appId: '1:568144474994:android:cd53ffe39f48c19001a3eb',
    messagingSenderId: '568144474994',
    projectId: 'salon-app-adabc',
    storageBucket: 'salon-app-adabc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOz9rZ638LS2nektb0NGMZF_s4YNoU8AI',
    appId: '1:568144474994:ios:ba37ca371481ed1401a3eb',
    messagingSenderId: '568144474994',
    projectId: 'salon-app-adabc',
    storageBucket: 'salon-app-adabc.firebasestorage.app',
    androidClientId: '568144474994-k8mhj5u8uso1ba54tg6k1ths0c5d03g9.apps.googleusercontent.com',
    iosClientId: '568144474994-klgheo1nd9vtlpqn2835kcr78i1g5ho4.apps.googleusercontent.com',
    iosBundleId: 'com.akshay.salonApp',
  );
}
